# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit_comment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14reddit_comment.proto\"s\n\rRedditComment\x12\x12\n\ncomment_id\x18\x01 \x02(\t\x12\x15\n\rsubmission_id\x18\x02 \x02(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x13\n\x0b\x63reated_utc\x18\x04 \x02(\t\x12\x14\n\x0cstreamed_utc\x18\x05 \x02(\t')



_REDDITCOMMENT = DESCRIPTOR.message_types_by_name['RedditComment']
RedditComment = _reflection.GeneratedProtocolMessageType('RedditComment', (_message.Message,), {
  'DESCRIPTOR' : _REDDITCOMMENT,
  '__module__' : 'reddit_comment_pb2'
  # @@protoc_insertion_point(class_scope:RedditComment)
  })
_sym_db.RegisterMessage(RedditComment)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REDDITCOMMENT._serialized_start=24
  _REDDITCOMMENT._serialized_end=139
# @@protoc_insertion_point(module_scope)
