# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit_submission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17reddit_submission.proto\"j\n\x10RedditSubmission\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x10\n\x08selftext\x18\x03 \x01(\t\x12\x13\n\x0b\x63reated_utc\x18\x04 \x02(\t\x12\x14\n\x0cstreamed_utc\x18\x05 \x02(\t')



_REDDITSUBMISSION = DESCRIPTOR.message_types_by_name['RedditSubmission']
RedditSubmission = _reflection.GeneratedProtocolMessageType('RedditSubmission', (_message.Message,), {
  'DESCRIPTOR' : _REDDITSUBMISSION,
  '__module__' : 'reddit_submission_pb2'
  # @@protoc_insertion_point(class_scope:RedditSubmission)
  })
_sym_db.RegisterMessage(RedditSubmission)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REDDITSUBMISSION._serialized_start=27
  _REDDITSUBMISSION._serialized_end=133
# @@protoc_insertion_point(module_scope)
