# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_price.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stock_price.proto\"\xbe\x01\n\nStockPrice\x12\x0e\n\x06ticker\x18\x01 \x02(\t\x12\x17\n\x0fmarket_time_utc\x18\x02 \x02(\t\x12\x12\n\nopen_price\x18\x03 \x02(\x01\x12\x12\n\nhigh_price\x18\x04 \x02(\x01\x12\x11\n\tlow_price\x18\x05 \x02(\x01\x12\x13\n\x0b\x63lose_price\x18\x06 \x02(\x01\x12\x11\n\tadj_close\x18\x07 \x01(\x01\x12\x0e\n\x06volume\x18\x08 \x02(\x03\x12\x14\n\x0cstreamed_utc\x18\t \x02(\t')



_STOCKPRICE = DESCRIPTOR.message_types_by_name['StockPrice']
StockPrice = _reflection.GeneratedProtocolMessageType('StockPrice', (_message.Message,), {
  'DESCRIPTOR' : _STOCKPRICE,
  '__module__' : 'stock_price_pb2'
  # @@protoc_insertion_point(class_scope:StockPrice)
  })
_sym_db.RegisterMessage(StockPrice)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKPRICE._serialized_start=22
  _STOCKPRICE._serialized_end=212
# @@protoc_insertion_point(module_scope)
